---
- hosts: promethues-server
  become: true
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present

    - name: Add Grafana GPG key
      apt_key:
        url: https://apt.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://apt.grafana.com stable main"
        state: present
        filename: grafana

    - name: apt update after adding Grafana repo
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes